info:
    name: VC4-API
    author: adventurerok
    desc: "The API package for VC4. This does not include the implementation."
    folder: "bin"
    install: "VC4-API.jar"
    data: "VC4-API.yml"
latest:
    recommended: "0.0"
    beta: "0.0"
    alpha: "0.0"
    dev: "0.0.0-203"
dev:
    "0.0.0-203":
        file: "VC4-API-0.0.0-203.jar"
        release: "22/04/2013"
        int: 203