info:
    name: VC4-ContentEditor
    author: adventurerok
    desc: "The Editor for VC4 data"
    folder: "bin"
    install: "VC4-ContentEditor.jar"
    data: "VC4-ContentEditor.yml"
    launch: "vc4.editor.EditorMain"
latest:
    recommended: "0.0"
    beta: "0.0"
    alpha: "0.0"
    dev: "0.0.0-203"
dev:
    "0.0.0-203":
        file: "VC4-ContentEditor-0.0.0-203.jar"
        release: "22/04/2013"
        int: 203