info:
    name: VC4-Server
    author: adventurerok
    desc: "The server for VC4"
    folder: "bin"
    install: "VC4-Server.jar"
    data: "VC4-Server.yml"
    launch: "vc4.server.Console"
latest:
    recommended: "0.0"
    beta: "0.0"
    alpha: "0.0"
    dev: "0.0.0-203"
dev:
    "0.0.0-203":
        file: "VC4-Server-0.0.0-203.jar"
        release: "22/04/2013"
        int: 203