package vc4.vanilla;

import vc4.api.Resources;
import vc4.api.graphics.texture.AnimatedTexture;

public class BlockTexture {

	public static int grassTop, grassSide, dirt, brick, stoneBrick, sandstoneBrick, obsidianBrick;
	public static int cobble, hellCobble, moss, hellrock, goldBrick, adamantiteBrick;
	public static int oakSapling, oakLeaves, oakWood, oakBase;
	public static int birchSapling, birchLeaves, birchWood, birchBase;
	public static int willowSapling, willowLeaves, willowWood, willowBase;
	public static int ashSapling, ashLeaves, ashWood, ashBase;
	public static int chestnutSapling, chestnutLeaves, chestnutWood, chestnutBase;
	public static int redwoodSapling, redwoodLeaves, redwoodWood, redwoodBase;
	public static int kapokSapling, kapokLeaves, kapokWood, kapokBase;
	public static int cypressSapling, cypressLeaves, cypressWood, cypressBase;
	public static int bookshelf, enchantedBookshelf, glass, fluid, obsidian, ore, stone;
	public static int sand, cracks, woodFront, cactusBottom, cactusTop, cactusSide;
	public static int vines, tallGrass, craftingTop, chestFront, chestTop, chestSide;
	public static int gravel, ladder, lightberries, algae, torch, cropsGrown, stakes;
	public static int farmland, wetFarmland, reeds, wire;
	public static int notGateInput, notGateOutput, notGateOther;
	public static int repeaterGateInput, repeaterGateOutput, repeaterGateOther;
	public static int andGateInput, andGateOutput, andGateOther, andGateInputA, andGateInputB;
	public static int orGateInput, orGateOutput, orGateOther, orGateInputA, orGateInputB;
	public static int norGateInput, norGateOutput, norGateOther, norGateInputA, norGateInputB;
	public static int nandGateInput, nandGateOutput, nandGateOther, nandGateInputA, nandGateInputB;
	public static int flipFlopInput, flipFlopOutput;
	public static int dataStorageInput, dataStorageOutput, dataStorageOther;
	public static int gapRepeaterGateInput, gapRepeaterGateOutput, gapRepeaterGateOther;
	public static int bitMonitor, monitorInput, wool;
	public static int presentSideBlue, presentTopBlue;
	public static int[] crops = new int[9];
	public static int[] craftingTables = new int[5];
	public static int digital[] = new int[10];

	public static void update() {
		AnimatedTexture tex = Resources.getAnimatedTexture("blocks");
		grassTop = tex.getArrayIndex("grasstop");
		grassSide = tex.getArrayIndex("grassside");
		dirt = tex.getArrayIndex("dirt");
		brick = tex.getArrayIndex("brick");
		stoneBrick = tex.getArrayIndex("stonebrick");
		sandstoneBrick = tex.getArrayIndex("sandstonebrick");
		obsidianBrick = tex.getArrayIndex("obsidianbrick");
		cobble = tex.getArrayIndex("cobble");
		hellCobble = tex.getArrayIndex("hellcobble");
		moss = tex.getArrayIndex("moss");
		hellrock = tex.getArrayIndex("hellrock");
		goldBrick = tex.getArrayIndex("goldbrick");
		adamantiteBrick = tex.getArrayIndex("adamantitebrick");
		oakSapling = tex.getArrayIndex("oaksapling");
		oakLeaves = tex.getArrayIndex("oakleaves");
		oakBase = tex.getArrayIndex("oakbase");
		oakWood = tex.getArrayIndex("oakwood");
		birchSapling = tex.getArrayIndex("birchsapling");
		birchLeaves = tex.getArrayIndex("birchleaves");
		birchBase = tex.getArrayIndex("birchbase");
		birchWood = tex.getArrayIndex("birchwood");
		willowSapling = tex.getArrayIndex("willowsapling");
		willowLeaves = tex.getArrayIndex("willowleaves");
		willowBase = tex.getArrayIndex("willowbase");
		willowWood = tex.getArrayIndex("willowwood");
		ashSapling = tex.getArrayIndex("ashsapling");
		ashLeaves = tex.getArrayIndex("ashleaves");
		ashBase = tex.getArrayIndex("ashbase");
		ashWood = tex.getArrayIndex("ashwood");
		chestnutSapling = tex.getArrayIndex("chestnutsapling");
		chestnutLeaves = tex.getArrayIndex("chestnutleaves");
		chestnutBase = tex.getArrayIndex("chestnutbase");
		chestnutWood = tex.getArrayIndex("chestnutwood");
		redwoodSapling = tex.getArrayIndex("redwoodsapling");
		redwoodLeaves = tex.getArrayIndex("redwoodleaves");
		redwoodBase = tex.getArrayIndex("redwoodbase");
		redwoodWood = tex.getArrayIndex("redwoodwood");
		kapokSapling = tex.getArrayIndex("kapoksapling");
		kapokLeaves = tex.getArrayIndex("kapokleaves");
		kapokBase = tex.getArrayIndex("kapokbase");
		kapokWood = tex.getArrayIndex("kapokwood");
		cypressSapling = tex.getArrayIndex("cypresssapling");
		cypressLeaves = tex.getArrayIndex("cypressleaves");
		cypressBase = tex.getArrayIndex("cypressbase");
		cypressWood = tex.getArrayIndex("cypresswood");
		stone = tex.getArrayIndex("stone");
		bookshelf = tex.getArrayIndex("bookshelves");
		enchantedBookshelf = tex.getArrayIndex("bookshelvesenchanted");
		glass = tex.getArrayIndex("glass");
		fluid = tex.getArrayIndex("fluid");
		obsidian = tex.getArrayIndex("obsidian");
		ore = tex.getArrayIndex("ore");
		sand = tex.getArrayIndex("sand");
		cracks = tex.getArrayIndex("cracks");
		woodFront = tex.getArrayIndex("woodfront");
		cactusSide = tex.getArrayIndex("cactusside");
		cactusTop = tex.getArrayIndex("cactustop");
		cactusBottom = tex.getArrayIndex("cactusbottom");
		vines = tex.getArrayIndex("vines");
		for (int d = 0; d < 9; ++d) {
			crops[d] = tex.getArrayIndex("weeds" + (d + 1));
		}
		tallGrass = tex.getArrayIndex("tallgrass");
		for (int d = 0; d < 2; ++d) {
			craftingTables[d] = tex.getArrayIndex("craftingtable" + (d + 1));
		}
		craftingTop = tex.getArrayIndex("brownwood");
		chestFront = tex.getArrayIndex("chestfront");
		chestSide = tex.getArrayIndex("chestside");
		chestTop = tex.getArrayIndex("chesttop");
		gravel = tex.getArrayIndex("gravel");
		ladder = tex.getArrayIndex("ladder");
		lightberries = tex.getArrayIndex("lightberries");
		algae = tex.getArrayIndex("algae");
		torch = tex.getArrayIndex("torch");
		cropsGrown = tex.getArrayIndex("weedsgrown");
		stakes = tex.getArrayIndex("stakes");
		farmland = tex.getArrayIndex("farmland");
		wetFarmland = tex.getArrayIndex("wetfarmland");
		reeds = tex.getArrayIndex("reeds");
		wire = tex.getArrayIndex("wire");
		notGateInput = tex.getArrayIndex("notgateinput");
		notGateOutput = tex.getArrayIndex("notgateoutput");
		notGateOther = tex.getArrayIndex("notgateoutput");
		repeaterGateInput = tex.getArrayIndex("repeatergateinput");
		repeaterGateOutput = tex.getArrayIndex("repeatergateoutput");
		repeaterGateOther = tex.getArrayIndex("repeatergateother");
		andGateInput = tex.getArrayIndex("andgateinput");
		andGateInputA = tex.getArrayIndex("andgateinputa");
		andGateInputB = tex.getArrayIndex("andgateinputb");
		andGateOutput = tex.getArrayIndex("andgateoutput");
		andGateOther = tex.getArrayIndex("andgateother");
		orGateInput = tex.getArrayIndex("orgateinput");
		orGateInputA = tex.getArrayIndex("orgateinputa");
		orGateInputB = tex.getArrayIndex("orgateinputb");
		orGateOutput = tex.getArrayIndex("orgateoutput");
		orGateOther = tex.getArrayIndex("orgateother");
		norGateInput = tex.getArrayIndex("norgateinput");
		norGateInputA = tex.getArrayIndex("norgateinputa");
		norGateInputB = tex.getArrayIndex("norgateinputb");
		norGateOutput = tex.getArrayIndex("norgateoutput");
		norGateOther = tex.getArrayIndex("norgateother");
		nandGateInput = tex.getArrayIndex("nandgateinput");
		nandGateInputA = tex.getArrayIndex("nandgateinputa");
		nandGateInputB = tex.getArrayIndex("nandgateinputb");
		nandGateOutput = tex.getArrayIndex("nandgateoutput");
		nandGateOther = tex.getArrayIndex("nandgateother");
		flipFlopInput = tex.getArrayIndex("flipflopinput");
		flipFlopOutput = tex.getArrayIndex("flipflopoutput");
		dataStorageInput = tex.getArrayIndex("datastorageinput");
		dataStorageOutput = tex.getArrayIndex("datastorageoutput");
		dataStorageOther = tex.getArrayIndex("datastorageother");
		gapRepeaterGateInput = tex.getArrayIndex("gaprepeatergateinput");
		gapRepeaterGateOutput = tex.getArrayIndex("gaprepeatergateoutput");
		gapRepeaterGateOther = tex.getArrayIndex("gaprepeatergateother");
		for (int d = 0; d < 10; ++d) {
			digital[d] = tex.getArrayIndex("digital" + d);
		}
		bitMonitor = tex.getArrayIndex("bitmonitor");
		monitorInput = tex.getArrayIndex("monitorinput");
		wool = tex.getArrayIndex("wool");
		presentSideBlue = tex.getArrayIndex("presentsideblue");
		presentTopBlue = tex.getArrayIndex("presenttopblue");
	}
}
