gui:
    name: "settings"
    type: "menu"
    columns: 1
    rows: 0
    fontsize: 18
    border: "fill"
    button:
        startx: 15
        starty: 15
        width: 246
        height: 30
        gapx: 15
        gapy: 15
colorscheme:
    class: "settingscroller"
    fontsize: 16
    text: "menu.settings.colorscheme"
    args:
        - "{o:colorscheme}"
    action: "setting:colorscheme:next"
    alt: "setting:colorscheme:last"
crosshair:
    class: "settingscroller"
    fontsize: 16
    text: "menu.settings.crosshair"
    args:
        - "{o:crosshair}"
    action: "setting:crosshair:next"
    alt: "setting:crosshair:last"
back:
    class: "button"
    text: "menu.back"
    action: "back"