info:
    name: VC4-Client
    author: adventurerok
    desc: "The Client game for VC4"
    folder: "bin"
    install: "VC4-Client.jar"
    data: "VC4-Client.yml"
    launch: "vc4.client.Launcher"
latest:
    recommended: "0.0"
    beta: "0.0"
    alpha: "0.0"
    dev: "0.0.0-203"
dev:
    "0.0.0-203":
        file: "VC4-Client-0.0.0-203.jar"
        release: "22/04/2013"
        int: 203